# Generated by Django 5.1.7 on 2025-04-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0002_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='card',
            name='cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
